
drop table if exists account CASCADE ;
drop table if exists transaction CASCADE ;
create table account (id bigint generated by default as identity, balance decimal(19,2), name varchar(255), primary key (id));
create table transaction (id bigint generated by default as identity, amount decimal(19,2), created_time_stamp timestamp, receiver_id bigint, sender_id bigint, primary key (id));
alter table transaction add constraint FKlb9w2lainsxqirtlwg231h1ir foreign key (receiver_id) references account;
alter table transaction add constraint FKtadyjb9m2aggujattt7k2b0gy foreign key (sender_id) references account;